name: CICD-SSH

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - name: ssh-deploy
      uses: appleboy/ssh-action@master      
      with:
        python-version: ${{ matrix.python-version }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd ${{ github.event.repository.name }}/cicd
          sh deploy_ssh.sh
